# Generated by Django 2.2.1 on 2019-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190605_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritions',
            name='calcium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='fat_calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='fibers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='iron',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='proteins',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='sat_fat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='sodium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='sugar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='total_carb',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='total_fat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='trans_fat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='vitamins',
            field=models.IntegerField(blank=True),
        ),
    ]
