# Generated by Django 2.2.1 on 2019-06-06 10:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190605_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
