# Generated by Django 2.2.1 on 2019-06-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190607_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='diet',
            new_name='suitableForDiet',
        ),
    ]
