# Generated by Django 2.2.1 on 2019-06-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190617_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='course',
            new_name='recipeCategory',
        ),
    ]
