# Generated by Django 2.2.1 on 2019-06-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190617_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='price',
            new_name='estimatedCost',
        ),
    ]
