# Generated by Django 2.2.1 on 2019-06-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190617_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='link',
            new_name='recipeYield',
        ),
    ]
