# Generated by Django 2.2.1 on 2019-06-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190618_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='list_date',
            new_name='datePublished',
        ),
    ]
