# Generated by Django 2.2.1 on 2019-06-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190618_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='nutritions',
            new_name='nutrition',
        ),
    ]
