# Generated by Django 2.2.1 on 2019-06-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190618_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
