# Generated by Django 2.2.1 on 2019-06-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190621_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeinstruction',
            old_name='name',
            new_name='text',
        ),
    ]
