# Generated by Django 2.2.1 on 2019-06-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190621_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='totalTime',
        ),
    ]
