# Generated by Django 2.2.1 on 2019-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190621_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookTime',
            field=models.TimeField(blank=True,),
         
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepTime',
            field=models.TimeField(blank=True,),
        ),    
    ]
